export const departmentsAndIDS = [
  { id: 15000, name: 'all departments' },
  { id: 24191, name: 'accessories' },
  { id: 16864, name: 'baby and child' },
  { id: 23237, name: 'cards' },
  { id: 17350, name: 'fashion' },
  { id: 25267, name: 'fine jewellery' },
  { id: 17578, name: 'food and drink' },
  { id: 24427, name: 'free delivery' },
  { id: 17607, name: 'garden' },
  { id: 17677, name: 'gifts' },
  { id: 25179, name: 'hampers' },
  { id: 17920, name: 'health and beauty' },
  { id: 17968, name: 'home' },
  { id: 18926, name: 'jewellery' },
  { id: 24955, name: 'parties' },
  { id: 19064, name: 'pets' },
  { id: 16846, name: 'prints and art' },
  { id: 23941, name: 'stationery' },
  { id: 24345, name: 'toys and games' },
  { id: 19119, name: 'trends' },
  { id: 19383, name: 'weddings' },
];

export const categoryBlocks = [
  { id: 1, name: 'gifts & cards', image: 'gifts_and_cards.jpg', href: '/gifts' },
  { id: 2, name: 'prints & art', image: 'pictures_and_prints.jpg', href: '/art' },
  {
    id: 3,
    name: "women's jewellery",
    image: 'womens_jewellery.jpg',
    href: '/jewellery/womens-jewellery',
  },
  {
    id: 4,
    name: "men's jewellery",
    image: 'mens_jewellery.jpg',
    href: '/jewellery/mens-jewellery',
  },
  { id: 5, name: 'home accesories', image: 'home_accessories.jpg', href: '/home/home-accessories' },
  { id: 6, name: 'garden', image: 'garden.jpg', href: '/garden' },
  { id: 7, name: 'baby and child', image: 'baby_and_child.jpg', href: '/baby-child' },
  { id: 8, name: 'wedding styling', image: 'wedding_styling.jpg', href: '/weddings' },
];
