export const FETCH_PAGE = 'FETCH_PAGE';
export const FETCH_PAGE_FULFILLED = 'FETCH_PAGE_FULFILLED';
export const FETCH_PAGE_REJECTED = 'FETCH_PAGE_REJECTED';

export const SET_PREVIEW_MODE = 'SET_PREVIEW_MODE';
export const SET_DEBUG = 'SET_DEBUG';
